# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PPS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PPS

  target 'PPSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PPSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
