# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PPS-Data' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PPS-Data
  platform :ios, '12.0'
  pod 'ResearchKit', '~> 1.0'

  target 'PPS-DataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PPS-DataUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
